name: viz
channels:
  - conda-forge
dependencies:
  - cartopy=0.23.0
  - dask=2024.8.2
  - datashader=0.16.3
  - descartes=1.1.0
  - fastparquet=2024.5.0
  - geopandas=1.0.1
  - geoviews=1.12.0
  - holoviews=1.19.1
  - hvplot=0.10.0
  - ipython=8.27.0
  - jupyter=1.1.1
  - jupyterlab=4.2.5
  - matplotlib=3.9.2
  - notebook=7.2.2
  - numpy=2.0.2
  - openpyxl=3.1.5
  - pandas=2.2.2
  - panel=1.4.5
  - scikit-learn=1.5.2
  - seaborn=0.13.2
