channels:
- conda-forge
dependencies:
- cartopy=0.22.0
- datashader=0.15.2
- descartes=1.1.0
- fastparquet=2023.8.0
- geopandas=0.14.0
- geoviews=1.10.1
- holoviews=1.18.0
- hvplot=0.9.0
- jupyterlab=4.0.7
- matplotlib=3.8.0
- notebook=7.0.6
- numpy=1.24.4
- openpyxl=3.1.2
- pandas=2.1.1
- panel=1.2.3
- scikit-learn=1.3.1
- seaborn=0.13.0
name: viz
