name: viz
channels:
  - conda-forge
dependencies:
  - seaborn
  - scikit-learn
  - numpy
  - pandas
  - jupyterlab
  - matplotlib
  - geopandas
  - descartes
  - datashader
  - holoviews
  - notebook
  - hvplot
  - cartopy
  - panel
  - openpyxl
  - geoviews
  - fastparquet
  - cryptography
